name: lab4
mgmt:
  network: mgmt-net
  ipv4-subnet: 100.200.20.0/24
topology:
  kinds:
    vr-ros:
        image: docker.io/vrnetlab/vr-routeros:6.47.9
    linux:
        image: ghcr.io/hellt/network-multitool
  nodes:
    R01.NY:
      kind: vr-ros
      mgmt-ipv4: 100.200.20.20
    R01.LND:
      kind: vr-ros
      mgmt-ipv4: 100.200.20.21
    R01.HKI:
      kind: vr-ros
      mgmt-ipv4: 100.200.20.22
    R01.SPB:
      kind: vr-ros
      mgmt-ipv4: 100.200.20.23
    R01.LBN:
      kind: vr-ros
      mgmt-ipv4: 100.200.20.24
    R01.SVL:
      kind: vr-ros
      mgmt-ipv4: 100.200.20.25
    PC1:
        kind: linux
        mgmt-ipv4: 100.200.20.26
    PC2:
        kind: linux
        mgmt-ipv4: 100.200.20.27
    PC3:
        kind: linux
        mgmt-ipv4: 100.200.20.28

  links:
    - endpoints: ["R01.NY:eth3", "R01.LND:eth2"]
    - endpoints: ["R01.NY:eth2", "PC2:eth"]
    - endpoints: ["R01.LND:eth4", "R01.HKI:eth3"]
    - endpoints: ["R01.LND:eth3", "R01.LBN:eth2"]
    - endpoints: ["R01.LBN:eth3", "R01.SVL:eth2"]
    - endpoints: ["R01.SVL:eth3", "PC3:eth"]
    - endpoints: ["R01.LBN:eth4", "R01.HKI:eth2"]
    - endpoints: ["R01.HKI:eth4", "R01.SPB:eth2"]
    - endpoints: ["R01.SPB:eth3", "PC1:eth"]