name: lab2-a
mgmt:
    network: mgmt-net
    ipv4-subnet: 100.200.20.0/24
topology:
    kinds:
        vr-ros:
            image: docker.io/vrnetlab/vr-routeros:6.47.9
        linux:
            image: ghcr.io/hellt/network-multitool  
    nodes:
        R01.MSK:
            kind: vr-ros
            mgmt-ipv4: 100.200.20.2
        R02.BRL:
            kind: vr-ros
            mgmt-ipv4: 100.200.20.3
        R03.FRT:
            kind: vr-ros
            mgmt-ipv4: 100.200.20.4
        PC1:
            kind: linux
            mgmt-ipv4: 100.200.20.5
        PC2:
            kind: linux
            mgmt-ipv4: 100.200.20.6
        PC3:
            kind: linux
            mgmt-ipv4: 100.200.20.7
    links:
        - endpoints: ["R01.MSK:eth2", "R02.BRL:eth2"]
        - endpoints: ["R01.MSK:eth3", "R03.FRT:eth3"]
        - endpoints: ["R01.MSK:eth4", "PC1:eth2"]
        - endpoints: ["R02.BRL:eth3", "R03.FRT:eth2"]
        - endpoints: ["R02.BRL:eth4", "PC2:eth4"]
        - endpoints: ["R03.FRT:eth4", "PC3:eth2"]